### PR TITLE
Add tvOS ua parser

### PR DESCRIPTION
**Pull request by sb2nov**
Add basic parser for new apple tvOS

### CODE REVIEW

**Comment by sb2nov** [comment]
@tobie @elsigh please take a look  ?

**Comment by commenthol** [comment]
Thanks a lot for your contribution.

**Comment by sb2nov** [comment]
Sorry about a noob question: How does this get reflected in the versions of uap-java ? Do I need to wait for a new build of that ?

**Comment by commenthol** [comment]
Waiting for a new build on uap-java might not be a good option. maven repo support is not yet in place but highly desired. 
Currently you'll need to include the regexes.yaml file from uap-core and build all by yourself.

**Pull request merged**
