### PR TITLE
added instagram to regex.yaml

### PR DESCRIPTION
**Pull request by excellentingenuity**
- This PR adds the instagram mobile app webview browser to the regex.yml file.

### CODE REVIEW

**Comment by commenthol** [comment]
@excellentingenuity: Please add a testcase with the user-agent concerned in `tests/test_ua.yaml`. 
Maybe you could also consider `[Ii]nstagram` as regex which might be faster, or even leave it as `Instagram` if there is yet no lowercase UA in the wild.

**Comment by excellentingenuity** [comment]
I updated the PR to use the faster regex and also tests for Instagram

**Comment by excellentingenuity** [comment]
Finally, have the test working, had issues with the regex.

**Comment by commenthol** [comment]
Hi @excellentingenuity, Would it be possible for you to squash these numerous commits into a single one?
Maybe consider
```
git reset --soft 31a2afb
git commit -m "added instagram to regex.yaml"
```
Then force push

**Comment by sunknudsen** [comment]
@excellentingenuity Can you please squash your numerous commits into a single one (https://github.com/ua-parser/uap-core/pull/262#issuecomment-326035000)? Once done, we will be able to evaluate your pull request. Perhaps this other pull request will do the job? https://github.com/ua-parser/uap-core/pull/307

**Comment by sunknudsen** [comment]
Pull request https://github.com/ua-parser/uap-core/pull/307 added Instagram user agents. Closing as duplicate.

**Pull request closed without merging**
