### PR TITLE
add MiuiBrowser and Mint Browser regexes

### PR DESCRIPTION
**Pull request by admitad-github**
fix uap-core lack of distinction between Mint and Miui browsers from Chrome.

### CODE REVIEW

**Comment by commenthol** [comment]
@admitad-github could you please rebase?

**Comment by polischouckserg** [comment]
@commenthol yes, I've done rebase. Thanks.

**Comment by admitad-github** [comment]
@commenthol yes, I've done rebase. Thanks.

**Comment by commenthol** [comment]
Thanks

**Pull request merged**
