### PR TITLE
Adding IE detection using Trident tokens

### PR DESCRIPTION
**Pull request by efouts**
Addresses #92

### CODE REVIEW

**Comment by efouts** [comment]
@tobie @elsigh @commenthol Thoughts?

**Comment by commenthol** [comment]
IMHO I would not mix engines with browsers. 
From my understanding the browser is given as MSIE, because that indicates the behaviour even if in compatibility mode.
If a detection of the compatibility mode is also desired, then I would suggest something like this:

````
  ...

  # MSIE 8 !== Trident/4
  - regex: '(MSIE) ([^8])\.(\d)+.* Trident[ /]4\.'
    family_replacement: 'IE compatibility mode (MSIE 8)'
  # MSIE 9 !== Trident/5
  - regex: '(MSIE) ([^9])\.(\d)+.* Trident[ /]5\.'
    family_replacement: 'IE compatibility mode (MSIE 9)'
  # MSIE 10 !== Trident/6
  - regex: '(MSIE) (6|7|8|9)\.(\d)+.* Trident[ /]6\.'
    family_replacement: 'IE compatibility mode (MSIE 10)'
  # MSIE 11 !== Trident/7
  - regex: '(MSIE) (6|7|8|9|10)\.(\d)+.* Trident[ /]7\.'
    family_replacement: 'IE compatibility mode (MSIE 11)'
  - regex: '([MS]?IE) (\d+)\.(\d+)'
    family_replacement: 'IE'

  ...
```
e.g.
```
Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/7.0; SLCC2; .NET ...

outputs: 
family: IE compatibility mode (MSIE 11) 
major: 9
minor: 0
```

Please note that these regexes are yet untested.
Any suggestions? Especially on the family_replacement naming?

**Comment by efouts** [comment]
@commenthol that seems pretty reasonable. ill update this and make the test cases.

**Comment by efouts** [comment]
@commenthol What are do you think about ```IE 11 Compatibility Mode``` vs ```IE Compatibility Mode (MSIE 11)```

**Comment by commenthol** [comment]
Sounds good

**Comment by lhm** [comment]
@efouts This patch works for me, anything holding this back from merging? It's certainly more exact than the current version. Regarding the suggestion from @commenthol : Personally I'd lean towards putting the actual browser version in the version fields, because I think it's generally what is most interesting when using this. But if it's indicated in the family I guess that's fine, too.

**Comment by stash1001** [comment]
@efouts Can this be merged.   We also use this to decided which Browser Versions we need to support so knowing the actual version is much more important to us.

**Comment by elsigh** [comment]
It sounds/looks like this change is in a good place but has conflicts that need resolution first.

**Comment by doomspork** [comment]
Any updates on whether or not this will be merged @efouts / @commenthol?

**Comment by elsigh** [comment]
I still see that the branch has conflicts.

**Comment by doomspork** [comment]
@elsigh if @efouts is unable to resolve the conflict would you be opposed to be re-submitting the PR without the conflict?

**Comment by elsigh** [comment]
@doomspork If you submit another PR without the conflict that includes a test then sure, we could take another PR and close this one out. @efouts may be otherwise occupied.

**Comment by doomspork** [comment]
Updated @ https://github.com/ua-parser/uap-core/pull/288 @elsigh 👍 

Thanks for your prompt response.

**Comment by elsigh** [comment]
merged #288 - closing this - thanks @doomspork for the quick PR!

**Pull request closed without merging**
