### PR TITLE
add regex and test for the Qwantify spider

### PR DESCRIPTION
**Pull request by christennant**
Qwantify spider has user agent string:

"Mozilla/5.0 (compatible; Qwantify/2.4w; +https://www.qwant.com/)/2.4w"

### CODE REVIEW

**Comment by christennant** [comment]
My apologies on the multiple commits!  The last merge is an attempt to squash them all into a single commit.

**Comment by commenthol** [comment]
@christennant Thanks for this PR. Would you mind to put your changes into just one commit? Your merge intent did not really clear the things.

**Comment by christennant** [comment]
ok, I think that should do it -- there's just one commit now.

**Comment by christennant** [comment]
since my PR has now been superseded by later PR's, and so has conflicts, will close this one and open a new one.

**Pull request closed without merging**
