### PR TITLE
Add Microsoft Office Word matcher

### PR DESCRIPTION
**Pull request by kokarn**
Very simple Office Word 2014 detection

### CODE REVIEW

**Comment by commenthol** [comment]
@kokarn Could you please rebase?

**Comment by kokarn** [comment]
I'm no expert with git I'm afraid. Is this good enough or should I simply re-do the pull request?

**Comment by commenthol** [comment]
Hi @kokarn, the PR is not ideal with all the foreign commits. Could you please perform the following steps from a terminal?
```
git pull origin master
git cherry-pick 64f57d250d7507803a152d023d520da71e090018
```
then resolve the conflict with a difftool, e.g.
```
meld tests/test_us.yaml
git add tests/*
git cherry-pick --continue
git push
```

**Comment by kokarn** [comment]
Sorry for the extra commits, messed up. Replaced the whole pr with #386 instead.

**Pull request closed without merging**
