### PR TITLE
Add composer / packagist support

### PR DESCRIPTION
**Pull request by ThaDafinser**
#114 so its possible to be installed by the PHP package manager

### CODE REVIEW

**Comment by ThaDafinser** [comment]
Since the last commit was in 24th Nov 2015 i try it with a ping (sorry for it)
@dmolsen @commenthol @tobie

**Comment by tobie** [comment]
Would prefer keeping this language agnostic as much as possible.

**Comment by ThaDafinser** [comment]
I know what u mean @tobie 

But i would really like to use this testsuite for the useragent comparison here https://github.com/ThaDafinser/UserAgentParserComparison

And there is already a `package.json` in the repo, which is also a bit language dependent.

Another benefit would be, that the git submodule [here](https://github.com/ua-parser/uap-php) could be removed

**Comment by tobie** [comment]
> And there is already a package.json in the repo, which is also a bit language dependent.

Well, that's there to run the test suite, so not really.

**Comment by ThaDafinser** [comment]
@tobie it is okay when il do it over my fork and register it as a package?

I wont modify anything else, so it should be ok with the `Apache License`

**Comment by tobie** [comment]
:+1:

**Pull request closed without merging**
