### PR TITLE
updating ua object to match implementations

### PR DESCRIPTION
**Pull request by diminished**
Renaming the ua.patchMinor attribute to ua.patch to match existing implementations

### CODE REVIEW

**Comment by Ironholds** [comment]
That's not how it works. Implementations match core, not the other way around. @tobie  ?

**Comment by diminished** [comment]
Yeah, but I noticed that the current implementations do not match what was defined in core (in the documentation at least).

**Comment by tobie** [comment]
It's actually missing `patch`, so you should add `patch` but not remove `patchMinor`.

**Comment by diminished** [comment]
Thanks for the feedback.  I noticed that some of the implementations are also producing patch and patchMinor for OS.  Should the specification be updated to include those attributes as well?

**Comment by tobie** [comment]
Darn, sorry, I thought your fix was for OS.

Here's what this shoud look like:

```
interface ua-parser-output {
  // …
  object ua: {                  // The "user_agent_parsers" result
    attribute string family;
    attribute string major;
    attribute string minor;
    attribute string patch;
  };
  object os: {                  // The "os_parsers" result
    attribute string family;
    attribute string major;
    attribute string minor;
    attribute string patch;
    attribute string patchMinor;
  };
  // …
};
```

@commenthol, can you confirm?

**Comment by commenthol** [comment]
Yes, I can confirm the proposed correction is ok.

**Pull request merged**
