### PR TITLE
Fix test and add new case for iPhone

### PR DESCRIPTION
**Pull request by theikkila**
Fixes this issue https://github.com/ua-parser/uap-scala/issues/24 here in upstream

### CODE REVIEW

**Comment by travisbrown** [comment]
@theikkila Once this is merged we can publish a new release of ua-scala.

**Comment by longzheng** [comment]
I've never seen this useragent out in the wild ``iPhone## CPU iPhone OS 10_2``

**Comment by elsigh** [comment]
yeah, me neither - any background on this one @theikkila?

**Comment by theikkila** [comment]
We have been analyzing user agents of very large finnish network. This and variations encountered there multiple times

**Pull request merged**
