### PR TITLE
Firefox OS and Firefox for iOS updates.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Reference https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Tests seem to fail due to an npm bug.

**Comment by commenthol** [comment]
@glogiotatidis can you please add some testcases to this PR. #79 should have fixed the CI Issue.

**Comment by glogiotatidis** [comment]
@commenthol Added tests. thanks!

**Comment by commenthol** [comment]
Thanks for contributing

**Pull request merged**
