### PR TITLE
Windows 10 detection

### PR DESCRIPTION
**Pull request by yozik04**

### CODE REVIEW

**Comment by mimmi20** [comment]
The first versions of Windows 10 used the Token `Windows NT 6.4`. You may add this too.

Possible Useragents are:
`Mozilla/5.0 (Windows NT 6.4; Trident/7.0; rv:11.0) like Gecko`
`Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0`
`Mozilla/5.0 (Windows NT 6.4; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0`

**Comment by yozik04** [comment]
Please merge. I have added all user agent strings that you wanted.

**Comment by commenthol** [comment]
According to http://www.theverge.com/2014/11/24/7274727/windows-10-nt-version-10 `Windows NT 6.4` agent represents the "Windows 10 Technical Preview". `Windows NT 10.0` will be the "final" version.
Is there a need to distinguish this?
I would like to merge this now and if required by the group to change the OS name in an upcoming PR.

**Comment by Krinkle** [comment]
Caused #67.

**Pull request merged**
