### PR TITLE
Fix ESPN Radio podcast catcher regex

### PR DESCRIPTION
**Pull request by asuhan**
Make it more precise and compatible with Boost.Regex syntax as well.

### CODE REVIEW

**Comment by sunknudsen** [comment]
@asuhan Hi, could you please add a test for your ESPN Radio regex to https://github.com/ua-parser/uap-core/blob/master/tests/test_ua.yaml? Thanks!

**Comment by asuhan** [comment]
Hello, it's already covered, for example: https://github.com/ua-parser/uap-core/blob/master/test_resources/podcasting_user_agent_strings.yaml#L364. My change doesn't break these tests and works with C++ as well (for reference: https://github.com/ua-parser/uap-cpp/issues/18).

**Comment by commenthol** [comment]
LGTM

**Comment by silviucpp** [comment]
any idea when this fix will be merged ?

**Comment by sunknudsen** [comment]
@asuhan @silviucpp Hey guys, the tests in the `test_resources` are legacy. Can you please add a test for your ESPN Radio regex to https://github.com/ua-parser/uap-core/blob/master/tests/test_ua.yaml? Once done, I will merge your pull request. Thanks!

**Comment by asuhan** [comment]
@sunknudsen As I've already pointed out, https://github.com/ua-parser/uap-core/blob/master/test_resources/podcasting_user_agent_strings.yaml#L364 contains tests for the regex I'm changing. They still pass; they look adequate. I have no idea how else to test this change.

**Comment by asuhan** [comment]
I've simply copied the tests to `tests/test_ua.yaml`, no idea if they pass since the PR has conflicts.

**Pull request merged**
