### PR TITLE
Brand model

### PR DESCRIPTION
**Pull request by commenthol**
Adds Brand-Model parsing. Detects a lot of new Devices and Brands.
Tests are currently separate withing `tests/test_device_brandmodel.yaml`.

### CODE REVIEW

**Comment by commenthol** [comment]
ping...

**Comment by tobie** [comment]
Doesn't seem to merge properly, mind looking into it?

**Comment by commenthol** [comment]
Travis CI still uses uap-ref-impl@0.1.0 (See [line 111](https://travis-ci.org/ua-parser/uap-core/builds/46534696)). In order to pass all tests, npm requires an update of "uap-ref-impl" with the version 0.2.0 checked in.
Can you please be so kind to checkout the latest "uap-ref-impl" and publish on npm? (See https://github.com/ua-parser/uap-ref-impl/issues/6)

Paste this into your terminal...

``` bash
# clone repo
git clone https://github.com/ua-parser/uap-ref-impl.git
cd uap-ref-impl
# pack the stuff
npm pack
# take a look whats inside
tar tvzf uap-ref-impl-0.2.0.tgz
# ... and out with it ... ;)
npm publish
```

**Comment by tobie** [comment]
Oh, sorry, I thought there was a merge conflict, not a test suite issue. My bad.

**Pull request merged**
