### PR TITLE
Adding Opera Neon Browser Detection

### PR DESCRIPTION
**Pull request by joshuawoolf87**
I've added detection support for the new [Opera Neon](https://www.opera.com/computer/neon) web browser.

### CODE REVIEW

**Comment by commenthol** [comment]
Hi @joshuawoolf87, your proposed regex pattern might conflict with quite old user-agents like this one:
```
PANTECH-EUROPA-U4000-orange/1.0 Obigo/Q04C MMS/1.2.0 profile/MIDP-2.0 configuration/CLDC-1.1
```
Can you please change the pattern to be more specific to Opera Neon?

**Comment by joshuawoolf87** [comment]
Hey @commenthol, I've done so now.

**Comment by commenthol** [comment]
Hi @joshuawoolf87, just realized, that your branch is quite outdated. Would you mind rebasing from current `master`? Maybe copy&paste your changes might be worth considering as well. Thanks.

**Comment by commenthol** [comment]
Did not head back from you. I did the rebase in #218. Hope that's fine with you. Thanks.

**Comment by joshuawoolf87** [comment]
Hey @commenthol, no problem, I had this on my to do list, but just hadn't got around to it yet. Thanks for taking care of it. :thumbsup:

**Pull request closed without merging**
