### PR TITLE
Fixes #461 - adds firefox mobile/tablet tests on Android

### LINKED ISSUE #461: Firefox Tablet/Mobile parsing fail for os
See https://github.com/ua-parser/uap-python/issues/84

### PR DESCRIPTION
**Pull request by karlcow**

### CODE REVIEW

**Comment by karlcow** [comment]
@miketaylr I was hesitant for the family in between Generic Smartphone, Generic mobile, etc. 
what do you think. Before proposing modifications of the regex, I would like to tackle what we call things.

**Comment by miketaylr** [comment]
> I was hesitant for the family in between Generic Smartphone, Generic mobile, etc.
> what do you think.

@karlcow I think smartphone makes sense here -- there are entries for "generic feature phone", so "generic smartphone" seems like a good parallel to that.

**Comment by commenthol** [comment]
@karlcow - still WIP?

**Comment by karlcow** [comment]
I'll pick up this this week again. Sorry for the delay. things happened.

**Comment by karlcow** [comment]
ok After checking it, this has been fixed in the most recent version.
https://github.com/ua-parser/uap-core/issues/461#issuecomment-623804359

**Pull request closed without merging**
