### PR TITLE
Add "Instagram" app

### PR DESCRIPTION
**Pull request by matAtWork**
Added tests for Android and iOS strings as seen in the wild, both passing with expected results.

### CODE REVIEW

**Comment by sunknudsen** [comment]
@matAtWork Thanks for the pull request. :) Is there a reason why you used `.` instead of ` ` or `\s` to match spaces in your regexes?

@commenthol What’s our policy for additions to `.gitignore`?

**Comment by commenthol** [comment]
I have no objection with regards to `.gitignore` additions.
`package-lock.json` is ok as it does not hurt - there are no updates published on npm.
`/.project` is difficult for me to classify as it seams to be something internal. So I would say this could be removed.

**Comment by matAtWork** [comment]
@sunknudsen  - No deep reasoning in using `.` over ` `. Feel free to update if you prefer.

@commenthol - `.project` was created by my editor. Again there's no good reason to either include or exclude it from `.gitignore`, but it's convenient for me personally :) 

If you wish me to make and push these changes, let me know, otherwise I'll let you proceed as you see fit.

**Comment by sunknudsen** [comment]
@matAtWork Please remove `.project` and we’re good to go. Thanks Mat!

**Comment by matAtWork** [comment]
Apologies for the delay. `.project` is now ignored and latest changes pulled. Please let me know if you need me to do anything else.

**Comment by sunknudsen** [comment]
Thanks @matAtWork. I removed .project from .gitignore as this line is editor-specific. Thanks for your contribution to the project.

**Pull request merged**
