### PR TITLE
Add Waterfox/Basilisk Firefox variants

### PR DESCRIPTION
**Pull request by kaplun**

### CODE REVIEW

**Comment by kaplun** [comment]
This should fix the issue we are having at ProtonMail, signaled in: https://github.com/getsentry/sentry/issues/7198

**Comment by sunknudsen** [comment]
@kaplun Thanks for the pull request.

@commenthol, should the Basilisk regex be placed at the end of the `#### SPECIAL CASES TOP ####` block vs top?

**Comment by commenthol** [comment]
The Basilisk regex (L4) should be moved somewhere around L113 where the other Firefox based rules can be found.

**Comment by kaplun** [comment]
Rebased.

**Pull request merged**
